### ISSUE TITLE
Dicionário de dados #1

### ISSUE THREAD

**Issue by renantleite** [MoonCancerBR/avanti-bootcamp-cdd#1]
- [x]  Coletar inicialmente os dados, seja por meio de download manual ou criando um script para download automático. Após a coleta, salve os dados em um arquivo na pasta data/raw.

- [x] Criar um dicionário de dados, uma estrutura que explicará os dados que serão trabalhados. Para cada variável do conjunto de dados, crie um dicionário Python contendo as seguintes informações:

-  Variável: Nome da coluna no pandas

-  Descrição: Descrição da coluna

- Tipo: Quantitativo ou qualitativo

- Subtipo: Nominal, ordinal, discreto, contínuo

**Comment by MoonCancerBR** [comment]
Feito :)

**Comment by renantleite** [comment]
:+1:
